# "debug", "info", "warning", "error", "critical"
log_level: 'info'

input_data_file: 'data/djia.parquet'

start_date: '2021-01-01'
end_date: '2022-01-01'

# weekly or monthly
plant_schedule: 'weekly'
